name: check_post_patch

on:
  workflow_run:
    workflows: ["docs"]
    types: 
      - completed

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download artifacts
      id: check-diff
      if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
      run: |
        python -m pip --disable-pip-version-check install requests
        python ./.scripts/extract_diff.py new_contents.diff ${{ github.event.workflow_run.artifacts_url }} ${{ github.event.workflow_run.html_url }} ${{ secrets.GITHUB_TOKEN }} > msg.txt
        if [ $? -eq 0 ]
        then
          echo "::set-output name=has-diff::true"
        fi;
    - name: Debug action
      uses: hmarr/debug-action@v1.0.0
